### ISSUE TITLE
Fetch?

### ISSUE THREAD

**Issue by IAmJulianAcosta** [mwpastore/ember-torii-demo#1]
Hi! I read your article, very nice way to implement torii, but I have a question, when should I use `fetch`? I see that you defined the function in the `adapter` but never used it, thanks!

**Comment by mwpastore** [comment]
@IAmJulianAcosta `fetch` is used when a user who has previously logged in returns to your site. `fetch` should do whatever it needs to do to resume the session—i.e. hit the server with an existing cookie or token you retrieve out of localStorage. If the session can't be resumed, `fetch` should fail and send the user back to the login screen or what have you. Does that make sense?

**Comment by IAmJulianAcosta** [comment]
Yes, is clear now, should be nice if in the example you do something with `fetch`, to clarify how it works.
